import typing
import collections.abc
import typing_extensions

def add_scrollback(text, text_type): ...
def autocomplete(context): ...
def banner(context): ...
def execute(context, is_interactive): ...
def shell_run(text): ...
