import typing
import collections.abc
import typing_extensions

class FunctionStore: ...

class ReturnStore:
    """Built-in immutable sequence.If no argument is given, the constructor returns an empty tuple.
    If iterable is specified the tuple is initialized from iterable's items.If the argument is a tuple, the return value is the same object.
    """

def fromxml(data): ...
def tag_module(mod_name, tags): ...
def tag_vars(tags, module="bpyml"): ...
def topretty_py(py_data, indent="    "): ...
def toxml(py_data, indent="    "): ...
